CREATE DATABASE IF NOT EXISTS web_data;
CREATE USER IF NOT EXISTS 'web_data'@'%' IDENTIFIED BY 'EQhOm2iBRfOG8RqTOjiamrUS/vzhDnzy';
GRANT ALL PRIVILEGES ON web_data.* TO 'web_data'@'%';
FLUSH PRIVILEGES;