FROM php:8.2-fpm

RUN apt update && apt install -y git

# For laravel
RUN docker-php-ext-install pdo_mysql

# Install Composer globally
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer