FROM node:18

# node 18, php 8.2, python3.10
RUN apt update && apt install -y git \
    php8.2-fpm \
    libxml2-dev \
    php8.2-xml \
    php8.2-curl \
    php8.2-mysql \
    php8.2-mbstring

# Install Composer globally
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY ./entrypoint.sh /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh